# Generated by Django 4.2.26 on 2025-11-27 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0108_alter_issueactivity_issue_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaloUserMetadata',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cv', models.CharField(blank=True, max_length=500, null=True)),
                ('cv_data', models.JSONField(blank=True, null=True)),
                ('zalo_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, default=dict, null=True)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zalo_metadata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zalo User Metadata',
                'verbose_name_plural': 'Zalo User Metadata',
                'db_table': 'zalo_user_metadata',
                'ordering': ('-created_at',),
            },
        ),
    ]
