# Generated by Django 4.2.26 on 2025-11-27 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0109_zalousermetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueDailyProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('day', models.DateField(help_text='The date for this daily progress entry')),
                ('daily_tasks', models.JSONField(default=dict, help_text='JSON field containing daily tasks and progress information')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the day', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_daily_progress', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='db.issue')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Daily Progress',
                'verbose_name_plural': 'Issue Daily Progress',
                'db_table': 'issue_daily_progress',
                'ordering': ['-day', '-created_at'],
                'unique_together': {('issue', 'day', 'created_by')},
            },
        ),
    ]
