# Generated by Django 4.2.26 on 2025-11-27 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0110_issuedailyprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedailyprogress',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_daily_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuedailyprogress',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_daily_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
